Vagrant.configure("2") do |config|
    config.vm.define "centos-test" do |db|
      db.vm.box = "centos/7"
      db.vm.hostname = "centos-test01"
      db.vm.network :private_network, ip: "10.10.10.10"
    
    config.vm.provider :virtualbox do |vb|
        vb.memory = 2048
	vb.cpus = 2
      end
    end
end
